name: HelpTicket
main: com.imdeity.helpticket.HelpTicket
version: 0.04
authors: [vanZeben, ImDeity]
description: This plugin is used for players to log problems, requests and complaints.
commands:
  ticket:
        aliases: [pe]
