name: HelpTicket
main: com.imdeity.helpticket.HelpTicketMain
version: 12.07.22
authors: [vanZeben, ImDeity]
description: This plugin is used for players to log problems, requests and complaints.
website: http://dev.bukkit.org/server-mods/helpticket
commands:
  Ticket:
        aliases: [pe]
