name: HelpTicket
main: com.rogue.helpticket.HelpTicketMain
version: ${project.version}
authors: [1Rogue, vanZeben, ImDeity]
description: This plugin is used for players to log problems, requests and complaints.
website: http://dev.bukkit.org/server-mods/helpticket
depend: [DeityAPI]
commands:
  Ticket:
        aliases: [pe]
